[package]
name = "my_allocator"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add the alloc crate as an optional dependency
alloc = { version = "0.0.0", optional = true }

[features]
# Feature to enable the global allocator
global_alloc = ["alloc"]
